### ISSUE TITLE
left to right not supported

### ISSUE THREAD

**Issue by shalom2552** [maoschanz/notes-extension-gnome#73] opened 2021-11-11 18:08 UTC
### RTL support (right-to-left hebrew)
Writhing notes in **hebrew**, while integrating some letters and numbers.
Using ubuntu 20.04

This are the problems I ran into:

1. Triple clicking to select full row, not working correctly.
2. End/Home keys not doing their purpose.
3. Left-to-right presents wrong.

Idea:
> Adding a basic options for words **bolding** and underlining e.t.c

**Comment by maoschanz** [comment] 2022-08-07 14:36
duplicate of #34

**Closed by maoschanz** 2022-08-07 14:36 UTC
